### ISSUE TITLE
incorrect hull for four points

### ISSUE THREAD

**Issue by ssured** [brian3kb/graham_scan_js#8]
These four points
[[223.25,30],[214.66796875,53.6015625],[213.79296875,38.6015625],[211.41796875,29.2265625]]
are not reduced to three, which they should be.

![image](https://cloud.githubusercontent.com/assets/2558804/12521404/c6e40250-c14a-11e5-8fdc-60ecdb5557b4.png)

Note that the pointer indicates the fourth point, but it does not have a marker in my usecase

**Comment by claudiobastos** [comment]
There is two possible hull for this points.
One to left, another to right (not showed).
Both are right. 
So, there should be another critéria to select one of them: like less area, or order of points.

I'm not the dev, just helping to detail this issue.

**Comment by ssured** [comment]
Please correct me if I'm wrong, but a hull should be a convex shape, right? Only the three points indicated with a marker should define the hull, the interior point is absorbed by the convex shape.

**Comment by claudiobastos** [comment]
I think you're right :')

We weren't thinking about  CONVEX hull...

sorry XD

**Comment by brian3kb** [comment]
Hi guys, I've had a quick look at this - and it looks like the naive auto-populating of less than 4 point hulls is causing the problem here - while this approach works well for mapping in Google / Bing maps, it appears to fail with these non-map related use cases.

So I will remove the naive auto-populating and force the small point sets through the checkpoints method and add some error handling to filter out the undefined values that will come through as a result.

Thanks for the bug report, much appreciated :)

**Comment by ssured** [comment]
Fast work, thanks!

**Comment by brian3kb** [comment]
Could you let me know if that resolves your issue? I added a test case based on the values you gave here - so it should be all good :)

Just published to npm, so you can update from the command line if your using from there.

Thanks!

**Comment by ssured** [comment]
Yeah it works, see screenshot below. I did update from NPM. Thank you sir!

![image](https://cloud.githubusercontent.com/assets/2558804/12553816/ce07e5f2-c379-11e5-9c1c-b8e0e4550675.png)
