### ISSUE TITLE
Computed hull is not convex

### ISSUE THREAD

**Issue by quicky84** [brian3kb/graham_scan_js#9]
I provide the following input to the implementation:
{{466, 231}, {469, 228}, {472, 226}, {476, 223}, {479, 221}, {483, 219}, {486, 216}, {489, 214},
{492, 211}, {495, 209}, {499, 207}, {503, 205}, {506, 203}, {510, 201}, {513, 200},
{517, 199}, {521, 197}, {525, 196}, {529, 194}, {532, 193}, {536,191}, {540, 190},
{544, 189}, {548, 188}, {552, 187}, {556, 187}, {563, 185}, {567, 184}, {571, 184},
{575, 183}, {579,   183}, {583, 183}, {587, 183}, {591, 183}, {595, 184}, {599, 185},
{602, 187}, {606, 189}, {610, 191}, {613, 193}, {617,195}, {620, 198}, {623, 200},
{627, 202}, {629, 205}, {633, 207}, {636, 210}, {639, 213}, {642, 215}, {647, 219},
{650, 222}, {653, 225}, {656, 228}, {658, 231}, {661, 234}, {663, 237}, {666, 240},
{667, 244}, {669, 248}, {671, 251}, {673, 252}, {674, 256}, {675, 258}}
which is a noisy (but recognizable) trace of an arc.

The output is as follows:
{{466, 231}, {469, 228}, {492, 211}, {489, 214}, {483, 219}, {503, 205}, {506, 203}, {510, 201},
{536, 191}, {552, 187}, {556, 187}, {563, 185}, {567, 184}, {571, 184}, {575, 183}, {591,183},
{599, 185}, {610, 191}, {617, 195}, {627, 202}, {633, 207}, {647, 219}, {656, 228}, {666, 240},
{673, 252}, {675, 258}}
which is not convex and moreover contains some "weird" points. See the picture below: black dashed line is the trace constituting the set of point to enclose, blue solid --- the hull

![failure](https://cloud.githubusercontent.com/assets/16148931/13216449/1d1d4cd4-d95c-11e5-8247-6d34bb051c3a.jpg)

**Comment by brian3kb** [comment]
Thanks for the feedback - looks like could be a JavaScript precision error due to the values being passed in - if you divide all your values by 10, you get an accurate hull.

The primary use-case for the library is for mapping using latitude and longitude values.

I have created this plunkr https://plnkr.co/zp2S0Tf5BTzewfUzqQVi showing your values (divided by 10) plotted on google maps - as you can see, a correct hull is shown.

By doing this, the output is:
[[466,231],[675,258],[673,252],[666,240],[661,234],[656,228],[647,219],[633,207],[627,202],[617,195],[610,191],[599,185],[595,184],[591,183],[575,183],[567,184],[552,187],[544,189],[536,191],[510,201],[506,203],[495,209],[492,211],[469,228]]

On the plunker, you can zoom right in to see the hull more clearly and the points that are contained within the hull (points shown here are all the points passed in, the bounding box connects the calculated hull points).

![image](https://cloud.githubusercontent.com/assets/1716071/13253946/ce18d136-da36-11e5-987c-5791ba9b6802.png)

**Comment by quicky84** [comment]
I created a pull request. See my comments there.
